### ISSUE TITLE
The Kick-off

### ISSUE THREAD

**Issue by eralp85** [swe574-spring23/SWE574#1]
- [x] Identify group members of the project
 
 > Cemre Kut
 > Ceyda Düzgeç
 > Emre Fişek
 > Maria Asif
 > Mümtaz Eralp Ünver
 > Semih Özkan
 > Şahin Kapan
 > Şehmuz Cacina 

- [x] Establish  communication channels
 
 > GitHub is set-up
 > Discord channel is set-up
 > Whatsapp channel is set-up

- [x]  Set the kick-off meeting

 > The functionality and structure of SWE573 projects is reviewed  
 > Weekly meeting time is determined

- [x]  New labels are created

**Comment by eralp85** [comment]
Feel free to add more if I  missed something

**Comment by sehmuzc** [comment]
Projects done at the previous semester were examined. It will be decided to start on a new project or on a previous project according to the requirements.

**Comment by sehmuzc** [comment]
The kick-off items have all been successfully completed.
