### ISSUE TITLE
Create Mockups For the User Badges, Search and Recommendations Part

### ISSUE THREAD

**Issue by sehmuzc** [swe574-spring23/SWE574#10]
Create the mockups for the user badges, annotations, search and recommendations part.

**Comment by sehmuzc** [comment]
The mockups for User Badges, Search and Recommendations have been completed.

**Comment by eralp85** [comment]
Wiki page is revised.  Sections for My Account, Spaces, Friends and Search has been updated.

**Comment by sehmuzc** [comment]
Wiki page has been successfully updated.

**Comment by sehmuzc** [comment]
https://github.com/swe574-spring23/SWE574/commit/9fa8ee4d3f8386ff3a74d9356c8d7930f4519da0
