### ISSUE TITLE
REFACTOR - Add Space Policy Text and Standards

### ISSUE THREAD

**Issue by sozkan4** [swe574-spring23/SWE574#112]
With current condition, space owners can only select posting permission in space policies. This feature needs to be extended.

<img width="598" alt="Screen Shot 2023-04-24 at 12 10 31" src="https://user-images.githubusercontent.com/35579090/233952337-ea3c416a-a38c-4f38-b5f6-a8ba0e0a60c2.png">

**Comment by ceydaduzgec** [comment]
@sozkan4 Who is responsible of this issue, do you know?

**Comment by sehmuzc** [comment]
The front end side has been corrected for this issue.
