### ISSUE TITLE
BUG - Space Creation Error - Badges

### ISSUE THREAD

**Issue by sozkan4** [swe574-spring23/SWE574#116]
When creating new space, the name and description box filled, and create space button is cliecked, relation "users_badge" does not exist error occured.
<img width="1159" alt="Screen Shot 2023-04-27 at 18 19 29" src="https://user-images.githubusercontent.com/35579090/234909240-28667e88-d55e-4a68-a568-e5a9aee4993b.png">

**Comment by sehmuzc** [comment]
Semih, could you try phtyon manage.py makemigrations and python manage.py migrate commands. If it does not work even with these commands could you please try to build your docker application from scratch and check if the error continues. Eralp or Ceyda may also have other comments in the issue. I assume that you may get the same error when creating a post or creating a comment as the user badges are added for these 3 models.

**Comment by sehmuzc** [comment]
This problem has been solved after making migrations it is possible to create spaces.
