### ISSUE TITLE
TEST - Creating Unit tests

### ISSUE THREAD

**Issue by MariaAsif135** [swe574-spring23/SWE574#118]
Issues related to website testing will be attached here

**Comment by MariaAsif135** [comment]
1.	User-related test cases:

- [x] Test user registration
- [x] Test user login
- [x] Test user logout
- [x] Test user profile update
- [x] Test user badge assignment and recognition

2.	Space-related test cases:

- [x] Test space creation
- [x] Test space deletion
- [x] Test space membership (addition/removal of members)
- [x] Test space policies (creation, modification, and enforcement)
- [x] Test space recommendation system
- [x] Test space search functionality

3.	Post-related test cases:

- [ ] Test post creation
- [x] Test post deletion
- [ ] Test post linking to multiple spaces
- [ ] Test duplicate link detection and confirmation
- [ ] Test post annotation (adding text or images)
- [x] Test post search functionality

4.	Tag-related test cases:

- [x] Test creation of descriptive tags via Wikidata
- [x] Test creation of informative tags
- [x] Test tag assignment to posts
- [x] Test tag-based post search

5.	Moderator-related test cases:

- [ ] Test moderator role assignment
- [ ] Test inspection and removal of abusive content
- [ ] Test warning system for disruptive behavior

6.	Recommendation-related test cases:

- [x] Test user recommendations (based on interests, space memberships, etc.)
- [x] Test space recommendations (similar spaces, popular spaces, etc.)
- [x] Test post recommendations (based on user preferences, tags, etc.)

**Comment by ceydaduzgec** [comment]
Can you also check the coverage when you are testing so that you can make sure you are covering all the lines of the related view?

**Comment by cemrekut** [comment]
guys i edited with the click button so when you finished you can select the box @efisek @MariaAsif135

**Comment by sehmuzc** [comment]
Unit tests have been added to the project successfully.
