### ISSUE TITLE
FEATURE - Deploy to EC2

### ISSUE THREAD

**Issue by ceydaduzgec** [swe574-spring23/SWE574#127]
- [ ] Exclude secret keys from the project files
- [ ] Create new keys for production environment
- [ ] Include new secret keys to `.env`file
- [ ] Change project files such as settings, docker, github workflows to get keys from `env`file
- [ ] Update `prod` branch of the project
- [ ] Deploy `prod`branch to EC2 instance

**Comment by sehmuzc** [comment]
The deployment will be made on Azure, so I am closing this issue on AWS.

**Comment by ceydaduzgec** [comment]
Deployed on AWS after discussion: http://ec2-52-91-248-162.compute-1.amazonaws.com
- port 81 will be opened or another ec2 will be used for annotation
- secret keys will be seperated

**Comment by sehmuzc** [comment]
Could you please examine these?
https://stackoverflow.com/questions/5517950/django-media-url-and-media-root

https://github.com/sehmuzc/SoftwareDevelopmentPractice/commit/adfc5919e33cad5d013a39dee6a2703ee5c70e68

**Comment by sehmuzc** [comment]
Mission completed.
