### ISSUE TITLE
BUG - ALL Annotations

### ISSUE THREAD

**Issue by eralp85** [swe574-spring23/SWE574#150]
Describe what were you doing and what caused the bug.
When checking the annotations on a specific post, we are seeing all the annotaions that are recorded.  We require specif annotation for specific post.
What do you think needs to be changed?
HTML and .JS shall be changed.

You can upload screen shot if needed.

**Comment by SahinKapan** [comment]
2d0b6bb1a109a3d9debe8819ff6738ddfbaf8758
