### ISSUE TITLE
BUG - Known bug list

### ISSUE THREAD

**Issue by ceydaduzgec** [swe574-spring23/SWE574#162]
- [x] 1- My Spaces Page -> Go to Space -> Goes to wrong URL

`http://127.0.0.1/spaces/myspaces/=%22/spaces/23/%22`

- [x] 2- Post without an image gives error:
`The 'image' attribute has no file associated with it.`

- [x] 3-  CSS error at the end of the page.
![image](https://github.com/swe574-spring23/SWE574/assets/37382270/d9e37506-813d-41a2-8ade-7cae3f765341)

- [ ] 4-  Generate data posts doesn't add labels:
![image](https://github.com/swe574-spring23/SWE574/assets/37382270/de9339d0-0957-4147-918a-e885a6f54307)

- [ ] 5- Generate data generates multiple data when run. It should check before creating new one if it already exists.

- [x] 6- When clicking on the tag, it doesn't go the related tag page.

- [x] 7- Image should be resized:
![image](https://github.com/swe574-spring23/SWE574/assets/37382270/a445176f-56bc-4d98-a81a-6f49f793554a)

- [ ] 8- Post editor shouldn't show the tag descriptions if semantic tag is not checked.
![image](https://github.com/swe574-spring23/SWE574/assets/37382270/aa8ad280-7789-4527-8a9f-8b2bc25aadda)

- [x] 9- My Spaces template should be the same with all spaces page.
- [x] 10 - Change profile photo should be added.
- [x] 11- Changing profile information page is not working.

**Comment by sehmuzc** [comment]
CSS error at my spaces has been solved.

**Comment by sehmuzc** [comment]
My Spaces template works fine now.

**Comment by sehmuzc** [comment]
Semantic tags will be investigated with Eralp. Generate Data issues will be handled by Semih. Other bugs have been corrected and merged. @ # #168 #167 #166 #165
