### ISSUE TITLE
FEATURE - Badge Images

### ISSUE THREAD

**Issue by sehmuzc** [swe574-spring23/SWE574#170]
The 9 images should be uploaded to production environment:
(https://github.com/swe574-spring23/SWE574/blob/dev/app_server/users/signals.py)

**Comment by cemrekut** [comment]
comment badges : 
![3b4ea1c0-c975-4c51-afe5-28305e57afab](https://github.com/swe574-spring23/SWE574/assets/56397129/5da8aef8-970b-4de9-a56e-bf5d60b0a871)
![d75ec705-22d6-47e9-ae85-6f99b5db7bf9](https://github.com/swe574-spring23/SWE574/assets/56397129/8216c6cb-f64a-4b2e-adcb-a7369fa93d42)
![fed48fe2-0d3f-48f5-86a0-45eb1e2999a7](https://github.com/swe574-spring23/SWE574/assets/56397129/b05ca49f-2185-49ee-9570-8e58dab55f22)

**Comment by cemrekut** [comment]
Follower badges: 
![WhatsApp Image 2023-05-27 at 16 55 38](https://github.com/swe574-spring23/SWE574/assets/56397129/e1c5054a-d17b-4a0d-8e2b-4c8ce5052acb)
![WhatsApp Image 2023-05-27 at 16 55 39](https://github.com/swe574-spring23/SWE574/assets/56397129/f04d4c2d-4457-4c2a-a606-54c2f6de9066)
![WhatsApp Image 2023-05-27 at 16 55 39 (1)](https://github.com/swe574-spring23/SWE574/assets/56397129/ae8d49fc-3dad-479d-9c84-aafcad44eed7)

**Comment by cemrekut** [comment]
Post Badges:
![WhatsApp Image 2023-05-27 at 16 57 51](https://github.com/swe574-spring23/SWE574/assets/56397129/2913a32b-0b7c-4ebc-a425-f1617816179a)
![WhatsApp Image 2023-05-27 at 16 57 51 (1)](https://github.com/swe574-spring23/SWE574/assets/56397129/496c42ab-9c77-439f-8fde-18fd5f28e7ef)
![WhatsApp Image 2023-05-27 at 16 57 50](https://github.com/swe574-spring23/SWE574/assets/56397129/89f68028-2eaf-4954-a144-db1f2821ff72)

**Comment by cemrekut** [comment]
Space Badges: 
![WhatsApp Image 2023-05-27 at 16 59 41](https://github.com/swe574-spring23/SWE574/assets/56397129/9198cb1b-601c-4194-9328-e88520b6fbb6)
![WhatsApp Image 2023-05-27 at 16 59 42](https://github.com/swe574-spring23/SWE574/assets/56397129/3cf869b7-059f-4d71-a641-6b4102f2a770)
![WhatsApp Image 2023-05-27 at 16 59 40](https://github.com/swe574-spring23/SWE574/assets/56397129/dadff437-f7e7-4e0b-a9fc-51d1c0cf964d)

**Comment by sehmuzc** [comment]
I have uploaded the images in details to the AWS environment.
