### ISSUE TITLE
Refine structure of weekly notes

### ISSUE THREAD

**Issue by sozkan4** [swe574-spring23/SWE574#19]
Instead of using bullet points using numeric lists would be beneficial for advisor to state specific points.

**Comment by ceydaduzgec** [comment]
@sozkan4 Can you check [this](https://github.com/swe574-spring23/SWE574/pull/17) pull request to see if it is enough to mark this issue as done?

**Comment by ceydaduzgec** [comment]
I am closing this one due to inactivity.
