### ISSUE TITLE
Space Recommendation Feature

### ISSUE THREAD

**Issue by sozkan4** [swe574-spring23/SWE574#21]
Recommendation feature will placed in two pages;

- Customer onboarding with ( More holistic designs to be investigated)
- Customers can have reccomendation according to their interaction with posts tags etc. There must be an algorithm to track interaction.
- Front End side might be planned also.

**Comment by cemrekut** [comment]
Customer onboarding with interests and suggestions users in the same area

**Comment by cemrekut** [comment]
html side -> @cemrekut @MariaAsif135 
back end side -> @cemrekut @sozkan4

**Comment by sehmuzc** [comment]
Space recommendations has been added based only on the number of posts that the space has. This functionality can be upgraded in the myspacelist view. 
#89

**Comment by sozkan4** [comment]
Change recommendations logic the current logic only has counting post numbers. More complex logic needed.
