### ISSUE TITLE
Annotation Framework

### ISSUE THREAD

**Issue by eralp85** [swe574-spring23/SWE574#25]
- [x] Research on annotation.

- [x] Documentation on annotation.

- [x] Coding of Annotation.

- [x] Testing of Annotation.

- [x] Merging with Production

**Comment by eralp85** [comment]
Annotation research and documentation is done. Please check Wiki page [Annotations ](https://github.com/swe574-spring23/SWE574/wiki/Annotations).

**Comment by sehmuzc** [comment]
Annotation framework has been implemented for further developments new issues can be opened.
https://github.com/swe574-spring23/SWE574/wiki/Annotation-Examples
