### ISSUE TITLE
Research spaces admin management feature

### ISSUE THREAD

**Issue by sozkan4** [swe574-spring23/SWE574#26]

**Comment by sozkan4** [comment]
space management examples to be searched. how many warnings should be given before kicking the banned users from the spaces? How admins can see or change in space settings?

**Comment by ceydaduzgec** [comment]
It's status is marked as Done, if it is done please close it. If not, please change the status.

**Comment by sehmuzc** [comment]
There is no description in the first part of the issue but I am closing the issue as we are near the end of the project and the main title is research.
