### ISSUE TITLE
Research user badges feature

### ISSUE THREAD

**Issue by efisek** [swe574-spring23/SWE574#28]

**Comment by sehmuzc** [comment]
Activity-based badges: You can assign badges to users based on how active they are on your website. For example, you can create badges for users who have made a certain number of posts, comments, or likes.

Time-based badges: You can assign badges to users based on how long they have been using your website. For example, you can create badges for users who have been members for a certain period of time, such as a month, a year, or longer.

Engagement-based badges: You can assign badges to users based on how engaged they are with other users on your website. For example, you can create badges for users who have received a certain number of likes or comments on their posts, or who have contributed to discussions on your website.

**Comment by efisek** [comment]
The research has been completed.
