### ISSUE TITLE
BUG - Post edit

### ISSUE THREAD

**Issue by ceydaduzgec** [swe574-spring23/SWE574#39]
When editing a post the form is empty. 
`post_edit` function should be inspected and changed accordingly.

![image](https://user-images.githubusercontent.com/37382270/224807009-a793816a-db8e-448a-b3a3-5b6708e16286.png)

**Comment by sehmuzc** [comment]
I will update the post_edit part in a new html file and will also update the view for post_edit so that the input values come prefilled with post values.

**Comment by sehmuzc** [comment]
#46 PostEditor page has been added. The functionality works fine now.
