### ISSUE TITLE
REFACTOR - Space Creation Code Blocks

### ISSUE THREAD

**Issue by sehmuzc** [swe574-spring23/SWE574#41]
**The codes for space model will be refactored*

Use POSTING_PERMISSION_CHOICES from the models.py so we don't need to copy-paste it to forms.py.
Add an empty new line at the end of create_space.html please?
Run the pre-commit linter to update the linter mistakes.
Delete SpaceForm.

**Comment by sehmuzc** [comment]
@ceydaduzgec Could you please put the commands to run in the terminal the pre-commit linter to a folder where everyone can reach easily such as wiki or project overall description parts.

**Comment by ceydaduzgec** [comment]
Hello @sehmuzc I already put them here: https://github.com/swe574-spring23/SWE574/blob/development/docs/developer-handbook/linting.md
I will update wiki and docs when I am done with documentation. Thanks for reminding me 👍🏼

**Comment by sehmuzc** [comment]
Spaceform has been deleted. #46

**Comment by sehmuzc** [comment]
Linting updates have been completed.
