### ISSUE TITLE
FEATURE - User Badges

### ISSUE THREAD

**Issue by efisek** [swe574-spring23/SWE574#47]
Users will earn badges that are based on the decided criteria:
- Activity-based
- Time-based
- Engagement-based

These earned badges will be shown in the user profile.

**Comment by sehmuzc** [comment]
Eralp implemented the user badges , I am closing the issue.

**Comment by cemrekut** [comment]
Hi @efisek @eralp85, i added all documents about badges, is there any problem for the visibility?
