### ISSUE TITLE
Draft Requirements & Mockups

### ISSUE THREAD

**Issue by sozkan4** [swe574-spring23/SWE574#5]
From the brief create draft requirements and mock ups in wiki

**Comment by eralp85** [comment]
Balsamiq framework is being used for creating mock-ups.

**Comment by eralp85** [comment]
The base for mock-up preparations has been shared. Multiple user login has been provided for group work.

**Comment by sozkan4** [comment]
Mock up study started for recommendation, space and profile/space management

**Comment by sozkan4** [comment]
Mock up study for spaces / policy and recommendation completed

**Comment by ceydaduzgec** [comment]
It's status is marked as Done, if it is done please close it. If not, please change the status.

**Comment by ceydaduzgec** [comment]
I am closing this one since we submitted our requirements to moodle.
