### ISSUE TITLE
REFACTOR -Space App Unit Tests Should be Enhanced

### ISSUE THREAD

**Issue by sehmuzc** [swe574-spring23/SWE574#64]
Space app tests.py file should be created and the create space, view space detail functions should be tested with unit tests.

**Comment by ceydaduzgec** [comment]
You can check the coverage of your code by following these steps:

[Use coverage.py](https://coverage.readthedocs.io/en/7.2.2/)

- Enter the interactive bash of the container by running `docker-compose exec app bash`
- Install coverage.py by running `pip install coverage`
- Run `coverage run manage.py test` or if you already have a test database:`coverage run manage.py test --keepdb`
- Run `coverage report` to see the report.
- For a nicer presentation, use `coverage html` to get annotated HTML listings detailing missed lines. Then open `htmlcov/index.html` in your browser.

**Comment by sehmuzc** [comment]
Space app tests.py file has been created and the create space, view space detail functions unit tests have been added.
