### ISSUE TITLE
REFACTOR - Change forms to be dynamic

### ISSUE THREAD

**Issue by ceydaduzgec** [swe574-spring23/SWE574#67]
[Related comment](https://github.com/swe574-spring23/SWE574/pull/66/files#r1148634902) 

More can be found in documentation: https://docs.djangoproject.com/en/4.1/topics/forms/#reusable-form-templates

**Comment by ceydaduzgec** [comment]
- add_comment_to_post.html
- post_edit.html
- post_editor.html -> make sure which one we are using and delete the other
- share.html
- create_space.html
- space_policies.html

You can take this code snippet  that Sehmuz wrotes as an example.

```html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {#{{ user_form.as_p }}#}
    {% for field in user_form %}
    <div class="mb-3">
        <label class="form-label">{{field.label}}</label>
        <input class="form-control" type="text" value="{{ field.value }}" >
    </div>
    {% endfor %}
    <div class="mb-3">
        <button type="submit" class="btn btn-primary"> Save changes</button>
    </div>

</form>
```

**Comment by sehmuzc** [comment]
Newer code blocks have been implemented with this proposed architecture.
