### ISSUE TITLE
BUG - Search Page Layout Front End

### ISSUE THREAD

**Issue by sozkan4** [swe574-spring23/SWE574#78]
When a search item executed, texts are mixed. Also SWE573 is seen below it must be SWE574. Please see images for details. 

<img width="1080" alt="Screen Shot 2023-03-28 at 15 07 05" src="https://user-images.githubusercontent.com/35579090/228231905-86e01c3e-f2ee-4fa4-8611-5abf514c3113.png">

**Comment by ceydaduzgec** [comment]
@SahinKapan According to  https://github.com/swe574-spring23/SWE574/issues/33 it should've been solved since you closed this issue. Can you double check the problem and fix it plase?

**Comment by sehmuzc** [comment]
This problem has been solved by base.html updates.
