### ISSUE TITLE
FEATURE - Semantic tag feature

### ISSUE THREAD

**Issue by ceydaduzgec** [swe574-spring23/SWE574#83]

**Comment by eralp85** [comment]
Finished the back-end. Working on front-end development.

**Comment by cemrekut** [comment]
> Finished the back-end. Working on front-end development.

Can we check before the lessons?

**Comment by ceydaduzgec** [comment]
@eralp85 Can you open a draft pull request so we can all see what you've been doing?

**Comment by eralp85** [comment]
Labels will be added.

**Comment by sehmuzc** [comment]
The description is not provided, a new issue can be opened for further developments.
