### ISSUE TITLE
FEATURE - Designing new user badges 

### ISSUE THREAD

**Issue by cemrekut** [swe574-spring23/SWE574#98]
Designing new badges with badge design website. 
https://badge.design/

**Comment by cemrekut** [comment]
For Comment Badges: (PNG and SVG)
![3b4ea1c0-c975-4c51-afe5-28305e57afab](https://user-images.githubusercontent.com/56397129/231720615-ae7fccb1-2a24-4aac-9461-d06aa68b99cb.png)
![30c272bf-3c0e-4d11-9ae0-da175222a2ec](https://user-images.githubusercontent.com/56397129/231720624-ef9e0302-20af-424a-8fc7-deb640c43ed1.svg)
![35ce0c0c-e6e6-4b98-a792-30bfead392eb](https://user-images.githubusercontent.com/56397129/231720625-696f313a-4d4c-4885-b091-62bc2f318d11.svg)
![8643c4dc-d777-4974-8b3f-4823fd9b1cc6](https://user-images.githubusercontent.com/56397129/231720629-650ee777-49c5-46fd-8b48-78be8094874b.svg)
![d75ec705-22d6-47e9-ae85-6f99b5db7bf9](https://user-images.githubusercontent.com/56397129/231720631-e0b97135-864e-4be4-94b3-0a771bfb90d4.png)
![fed48fe2-0d3f-48f5-86a0-45eb1e2999a7](https://user-images.githubusercontent.com/56397129/231720632-e5199664-ce97-42b2-94d2-1b9ffc8dd790.png)

**Comment by cemrekut** [comment]
@ceydaduzgec @efisek @sehmuzc @eralp85  hi Are these templates ok for everyone?  I uploaded in both formats

**Comment by ceydaduzgec** [comment]
Looks great! Where will you be uploading these in the project folder?
