### ISSUE TITLE
BUG - Post List View Updates

### ISSUE THREAD

**Issue by sehmuzc** [swe574-spring23/SWE574#99]
1. The Post List view should be updated to get the posts of the followed users. Currently it is commented.
2. In the friends page when the Follow button is clicked the user should be followed and the link should change to unfollow.
3. The tags should be displayed in the post list page. It may have been removed after the bookmarking developments.
4-The project name should be SWE574 on the base.html file.

**Comment by ceydaduzgec** [comment]
@sehmuzc I am done with the first 3 but I don't understand what you mean by 4. Can you explain it further please?

**Comment by ceydaduzgec** [comment]
Done with PR https://github.com/swe574-spring23/SWE574/pull/110. Thanks to @sehmuzc
